services:
  mongo:
    image: mongo:8
    container_name: ecommerce-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: unless-stopped
    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017/ecommerce_db1

    volumes:
      - ./backend/uploads:/app/uploads

    depends_on:
      mongo:
        condition: service_healthy

    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_ENABLE_MSW: "false"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo_data: